import { createElement } from 'lwc';
import Lwc_ssc_getAccounts from 'c/lwc_ssc_getAccounts';

describe('c-lwc-ssc-get-accounts', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-ssc-get-accounts', {
            is: Lwc_ssc_getAccounts
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});